[package]
name = "simple-json-parser"
version = "0.0.5"
edition = "2021"
description = "No allocation JSON key-value parser with comment support"
authors = ["Ben <kaleidawave@gmail.com>"]
license = "MIT"
keywords = ["json", "parser", "no-allocation", "comments"]
categories = ["parsing", "web-programming"]
repository = "https://github.com/kaleidawave/simple-json-parser"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[features]
extras = []

[lib]
path = "lib.rs"
crate-type = ["cdylib", "rlib"]

[target.'cfg(target_family = "wasm")'.dependencies]
wasm-bindgen = "0.2"
# console_error_panic_hook = "0.1"
# js-sys = "0.3"

[lints.clippy]
pedantic = "deny"

# For testing only
[dev-dependencies]
serde_json = "1.0.138"
